name: akrilii
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0-190.1.beta <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.4.0
  flutter_screenutil: ^5.9.1
  flutter_svg: ^2.0.10+1
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_bloc: ^8.1.5
  bloc: ^8.1.4
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/akrilii-logo.png"
  android_gravity: fill
  android: true
  ios: true
  web: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/akrilii-logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/lang/

  fonts:
    - family: Bold
      fonts:
        - asset: assets/fonts/FiraSans-BlackItalic.ttf

    - family: Light
      fonts:
        - asset: assets/fonts/FiraSans-Light.ttf

    - family: Medium
      fonts:
        - asset: assets/fonts/FiraSans-Medium.ttf

    - family: Reguler
      fonts:
        - asset: assets/fonts/Kanit-Regular.ttf
